import { PACK_META, PROBE_BY_ID } from "@/lib/probes/catalog";
import type { ScanRecord } from "@/lib/probes/types";
import { riskLabel, scoreResults, tally } from "./risk";

export function reportMarkdown(scan: ScanRecord) {
  const score = scoreResults(scan.results);
  const t = tally(scan.results);
  const lines: string[] = [
    `# RedTeamForge scan report`,
    ``,
    `**${scan.name}**`,
    ``,
    `- Date: ${new Date(scan.createdAt).toISOString()}`,
    `- Target: ${scan.target.label} (${scan.target.model})`,
    `- Risk score: ${score}/100 (${riskLabel(score)})`,
    `- Hits: ${t.hit} · Partial: ${t.partial} · Blocked: ${t.blocked} · Errors: ${t.error}`,
    `- Duration: ${(scan.durationMs / 1000).toFixed(1)}s`,
    ``,
    `## System prompt under test`,
    ``,
    "```",
    scan.systemPrompt.trim(),
    "```",
    ``,
    `## Findings`,
    ``,
  ];

  const ordered = [...scan.results].sort((a, b) => rank(a.verdict) - rank(b.verdict));
  for (const r of ordered) {
    const p = PROBE_BY_ID[r.probeId];
    if (!p) continue;
    lines.push(`### ${p.name} — ${r.verdict.toUpperCase()}`);
    lines.push(``);
    lines.push(`- OWASP ${p.owasp} · ${PACK_META[p.pack].label} · ATLAS ${p.atlas}`);
    lines.push(`- Severity: ${p.severity}`);
    if (r.evidence) lines.push(`- Evidence: ${r.evidence}`);
    if (r.error) lines.push(`- Error: ${r.error}`);
    lines.push(``);
    lines.push(`**Payload**`);
    lines.push(``);
    lines.push("```");
    lines.push(p.payload);
    lines.push("```");
    lines.push(``);
    lines.push(`**Response**`);
    lines.push(``);
    lines.push("```");
    lines.push(r.response || "(empty)");
    lines.push("```");
    lines.push(``);
  }

  if (scan.analysis) {
    const a = scan.analysis;
    lines.push(`## Analyst notes`);
    lines.push(``);
    lines.push(a.executiveSummary);
    lines.push(``);
    lines.push(`Residual risk: ${a.residualRisk}`);
    lines.push(``);
    if (a.systemPromptAdvice.length) {
      lines.push(`### Prompt hardening`);
      lines.push(``);
      for (const tip of a.systemPromptAdvice) lines.push(`- ${tip}`);
      lines.push(``);
    }
  }

  lines.push(`---`);
  lines.push(`Generated by RedTeamForge. Self-hosted. No vendor lock-in.`);
  lines.push(``);
  return lines.join("\n");
}

function rank(v: string) {
  if (v === "hit") return 0;
  if (v === "partial") return 1;
  if (v === "error") return 2;
  if (v === "inconclusive") return 3;
  return 4;
}

export function reportJson(scan: ScanRecord) {
  return JSON.stringify(
    {
      generator: "RedTeamForge",
      ...scan,
      score: scoreResults(scan.results),
      risk: riskLabel(scoreResults(scan.results)),
    },
    null,
    2,
  );
}
