import { PACK_META, PROBE_BY_ID } from "@/lib/probes/catalog";
import type { ScanRecord } from "@/lib/probes/types";
import { riskLabelFor, scoreResults, tally } from "./risk";

/**
 * Model responses are attacker-influenced and routinely contain ``` — a
 * fence at least one backtick longer than anything inside the content is
 * the only thing keeping it from breaking out of the code block.
 */
function fenceFor(content: string) {
  const runs = content.match(/`{3,}/g) ?? [];
  const longest = runs.reduce((max, run) => Math.max(max, run.length), 2);
  return "`".repeat(longest + 1);
}

/** One-line evidence/error text can't be fenced — neutralize backticks and newlines. */
function inline(text: string) {
  return text.replace(/`/g, "′").replace(/\s+/g, " ").slice(0, 300);
}

export function reportMarkdown(scan: ScanRecord) {
  const score = scoreResults(scan.results);
  const t = tally(scan.results);
  const lines: string[] = [
    `# RedTeamForge scan report`,
    ``,
    `**${scan.name}**`,
    ``,
    `- Date: ${new Date(scan.createdAt).toISOString()}`,
    `- Target: ${scan.target.label} (${scan.target.model})`,
    `- Risk score: ${score}/100 (${riskLabelFor(scan.results)})`,
    `- Hits: ${t.hit} · Partial: ${t.partial} · Blocked: ${t.blocked} · Errors: ${t.error}`,
    `- Duration: ${(scan.durationMs / 1000).toFixed(1)}s`,
    ``,
    `## System prompt under test`,
    ``,
  ];

  const promptFence = fenceFor(scan.systemPrompt);
  lines.push(promptFence, scan.systemPrompt.trim(), promptFence, ``);
  lines.push(`## Findings`, ``);

  const ordered = [...scan.results].sort((a, b) => rank(a.verdict) - rank(b.verdict));
  for (const r of ordered) {
    const p = PROBE_BY_ID[r.probeId];
    if (!p) continue;
    lines.push(`### ${p.name} — ${r.verdict.toUpperCase()}`);
    lines.push(``);
    lines.push(`- OWASP ${p.owasp} · ${PACK_META[p.pack].label} · ATLAS ${p.atlas}`);
    lines.push(`- Severity: ${p.severity}`);
    if (r.evidence) lines.push(`- Evidence: ${inline(r.evidence)}`);
    if (r.error) lines.push(`- Error: ${inline(r.error)}`);
    lines.push(``);
    const payloadFence = fenceFor(p.payload);
    lines.push(`**Payload**`, ``, payloadFence, p.payload, payloadFence, ``);
    const response = r.response || "(empty)";
    const responseFence = fenceFor(response);
    lines.push(`**Response**`, ``, responseFence, response, responseFence, ``);
  }

  if (scan.analysis) {
    const a = scan.analysis;
    lines.push(`## Analyst notes`, ``);
    lines.push(inline(a.executiveSummary), ``);
    lines.push(`Residual risk: ${inline(a.residualRisk)}`, ``);
    if (a.systemPromptAdvice.length) {
      lines.push(`### Prompt hardening`, ``);
      for (const tip of a.systemPromptAdvice) lines.push(`- ${inline(tip)}`);
      lines.push(``);
    }
  }

  lines.push(`---`);
  lines.push(`Generated by RedTeamForge. Self-hosted. No vendor lock-in.`);
  lines.push(``);
  return lines.join("\n");
}

function rank(v: string) {
  if (v === "hit") return 0;
  if (v === "partial") return 1;
  if (v === "error") return 2;
  if (v === "inconclusive") return 3;
  return 4;
}

export function reportJson(scan: ScanRecord) {
  const score = scoreResults(scan.results);
  return JSON.stringify(
    {
      generator: "RedTeamForge",
      ...scan,
      score,
      risk: riskLabelFor(scan.results),
    },
    null,
    2,
  );
}
